# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.2.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: tuannghianguyen1509@gmail.com
author_name: glighter
contract_name: lesson_compile
deployment_language: python
preset_name: production
project_name: smart-contract-be-prod

